#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section

[options]
    default_indent = 2
    expand_tab = true
[[layers]]
  name = "lang#python"
[[layers]]
  name = "colorscheme"
[options]
    colorscheme = "desert"
    colorscheme_bg = "dark"
[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

[options]
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#latex"
 
  
[options]
  bootstrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'  

